import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>PostThread on Mastodon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gradient-radial from-[#2D2C2A] to-[#120D16] ">
        <div className="h-screen w-screen bg-[url(/bg.png)] bg-contain bg-right bg-no-repeat">
          <div className="flex h-screen w-2/3 flex-col items-center justify-center space-y-12 text-[#607686]">
            <h1 className="text-5xl">PostThread on Mastodon</h1>
            <div className="mx-auto w-1/2 space-y-4 text-justify">
              <h3 className="text-2xl text-[#727265]">
                Social Media that Rewards Instead of Extracts
              </h3>
              <h5 className=" text-lg text-[#696863]">
                PostThread gives social media users control over their feed,
                data and privacy. We compensate content creators in crypto for
                the value they provide.
              </h5>
            </div>
            <button className="w-56 rounded-md border-4 border-[#5B5A4D] bg-[#607686] p-4 text-xl font-bold text-[#222220]">
              <Link href="https://postthread.xyz">Go to PostThread</Link>
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
